export const layoutConfig = [
  {
    layoutid: "000",
    name: "Customize Design",
    category: "Custom",
    originalPrice: "RM70.00",
    discountedPrice: "RM60.00",
    images: [
      "/media/cardSelection/card-0/main.png",
      "/media/cardSelection/card-3/main.png",
      "/media/cardSelection/card-5/main.png",
      "/media/cardSelection/card-6/main.png",
      "/media/cardSelection/card-9/main.png",
    ],
    description:
      "Customize digital invitation card for those who wants to express their own creativity on digital invitation card",
    demo: "",
    features: [
      "RSVP + Admin Dashboard incl.",
      "Wishes",
      "Google Map Location / Waze Location",
      "Choose any song from Youtube",
      "Link to Whatsapp & Phone Call",
      "Add Photo section (Upon request)",
      "Live support during Event Day",
    ],
  },
  {
    layoutid: "001",
    name: "Light Pink Rosie",
    category: "Wedding",
    originalPrice: "RM60.00",
    discountedPrice: "RM50.00",
    images: [
      "/media/cardSelection/card-1/main.png",
      "/media/cardSelection/card-1/2-image.png",
    ],
    description:
      "Light Pink Rosie demonstrates the color of pink mix with flowers. By having a soft theme colors, it will surely brighten your guests mood.",
    demo: "/layout1-example",
    features: [
      "RSVP + Admin Dashboard incl.",
      "Wishes",
      "Google Map Location / Waze Location",
      "Choose any song from Youtube",
      "Link to Whatsapp & Phone Call",
      "Add Photo section (Upon request)",
      "Live support during Event Day",
    ],
  },
  {
    layoutid: "002",
    name: "Majestic Dark Brown",
    category: "Wedding",
    originalPrice: "RM60.00",
    discountedPrice: "RM50.00",
    images: [
      "/media/cardSelection/card-2/main.png",
      "/media/cardSelection/card-2/2-image.png",
    ],
    description:
      "Dark premium theme colors blended with soft color hand-writting. Mix with golden colors",
    demo: "/layout2-example",
    features: [
      "RSVP + Admin Dashboard incl.",
      "Wishes",
      "Google Map Location / Waze Location",
      "Choose any song from Youtube",
      "Link to Whatsapp & Phone Call",
      "Add Photo section (Upon request)",
      "Live support during Event Day",
    ],
  },
  {
    layoutid: "003",
    name: "Tulips In The Morning",
    category: "Wedding",
    originalPrice: "RM60.00",
    discountedPrice: "RM50.00",
    images: [
      "/media/cardSelection/card-3/main.png",
      "/media/cardSelection/card-3/2-image.png",
    ],
    description:
      "Refreshing looks brought in by Tulips with combination of purple , blue and green color. One of highest subscribed by our customer. Surely this design will never dissapoint you",
    demo: "/layout3-example",
    features: [
      "RSVP + Admin Dashboard incl.",
      "Wishes",
      "Google Map Location / Waze Location",
      "Choose any song from Youtube",
      "Link to Whatsapp & Phone Call",
      "Add Photo section (Upon request)",
      "Live support during Event Day",
    ],
  },
  {
    layoutid: "004",
    name: "Cinnamon Blue Petal",
    category: "Wedding",
    originalPrice: "RM60.00",
    discountedPrice: "RM50.00",
    images: [
      "/media/cardSelection/card-4/main.png",
      "/media/cardSelection/card-4/2-image.png",
    ],
    description:
      "Mixture of soft and dark color creates a harmony scenery that will surely make your guest feels calm.",
    demo: "/layout4-example",
    features: [
      "RSVP + Admin Dashboard incl.",
      "Wishes",
      "Google Map Location / Waze Location",
      "Choose any song from Youtube",
      "Link to Whatsapp & Phone Call",
      "Add Photo section (Upon request)",
      "Live support during Event Day",
    ],
  },
  {
    layoutid: "005",
    name: "Flourish Gloom",
    category: "Wedding",
    originalPrice: "RM60.00",
    discountedPrice: "RM50.00",
    images: [
      "/media/cardSelection/card-5/main.png",
      "/media/cardSelection/card-5/2-image.png",
    ],
    description:
      "Mixture of soft and dark color creates a harmony scenery that will surely make your guest feels calm.",
    demo: "/layout5-example",
    features: [
      "RSVP + Admin Dashboard incl.",
      "Wishes",
      "Google Map Location / Waze Location",
      "Choose any song from Youtube",
      "Link to Whatsapp & Phone Call",
      "Add Photo section (Upon request)",
      "Live support during Event Day",
    ],
  },
  {
    layoutid: "006",
    name: "Sky Ambience Breath",
    category: "Wedding",
    originalPrice: "RM60.00",
    discountedPrice: "RM50.00",
    images: [
      "/media/cardSelection/card-6/main.png",
      "/media/cardSelection/card-6/2-image.png",
    ],
    description:
      "Combination of light green and soft brown surely will provide you with great deep breathing look",
    demo: "/layout6-example",
    features: [
      "RSVP + Admin Dashboard incl.",
      "Wishes",
      "Google Map Location / Waze Location",
      "Choose any song from Youtube",
      "Link to Whatsapp & Phone Call",
      "Add Photo section (Upon request)",
      "Live support during Event Day",
    ],
  },
  {
    layoutid: "007",
    name: "Black Gold Label",
    category: "Wedding",
    originalPrice: "RM60.00",
    discountedPrice: "RM50.00",
    images: [
      "/media/cardSelection/card-7/main.png",
      "/media/cardSelection/card-7/2-image.png",
    ],
    description:
      "Premium black and gold look. Combination of majestic colors designed with modest art will make your card look ultra exclusive !",
    demo: "/layout7-example",
    features: [
      "RSVP + Admin Dashboard incl.",
      "Wishes",
      "Google Map Location / Waze Location",
      "Choose any song from Youtube",
      "Link to Whatsapp & Phone Call",
      "Add Photo section (Upon request)",
      "Live support during Event Day",
    ],
  },
  {
    layoutid: "008",
    name: "Vitamin Sea",
    category: "Wedding",
    originalPrice: "RM60.00",
    discountedPrice: "RM50.00",
    images: [
      "/media/cardSelection/card-8/main.png",
      "/media/cardSelection/card-8/2-image.png",
    ],
    description:
      "Presenting blue flowers mimicking sea to display calmness with minimalism look. One of our best seller that will surely make your guest fall in love with the design",
    demo: "/layout8-example",
    features: [
      "RSVP + Admin Dashboard incl.",
      "Wishes",
      "Google Map Location / Waze Location",
      "Choose any song from Youtube",
      "Link to Whatsapp & Phone Call",
      "Add Photo section (Upon request)",
      "Live support during Event Day",
    ],
  },
  {
    layoutid: "009",
    name: "Evening Turquoise Pastel",
    category: "Wedding",
    originalPrice: "RM60.00",
    discountedPrice: "RM50.00",
    images: [
      "/media/cardSelection/card-9/main.png",
      "/media/cardSelection/card-9/2-image.png",
    ],
    description:
      "Turqoise pastel theme color designed to express softness and light to provide you a calm and refreshing look",
    demo: "/layout9-example",
    features: [
      "RSVP + Admin Dashboard incl.",
      "Wishes",
      "Google Map Location / Waze Location",
      "Choose any song from Youtube",
      "Link to Whatsapp & Phone Call",
      "Add Photo section (Upon request)",
      "Live support during Event Day",
    ],
  },
  {
    layoutid: "010",
    name: "Aurora Glimpse",
    category: "Wedding",
    originalPrice: "RM60.00",
    discountedPrice: "RM50.00",
    images: [
      "/media/cardSelection/card-10/main.png",
      "/media/cardSelection/card-10/2-image.png",
    ],
    description:
      "A little bit aurora green color mix with light brown. A combination of soft colors to put femine vibes",
    demo: "/layout10-example",
    features: [
      "RSVP + Admin Dashboard incl.",
      "Wishes",
      "Google Map Location / Waze Location",
      "Choose any song from Youtube",
      "Link to Whatsapp & Phone Call",
      "Add Photo section (Upon request)",
      "Live support during Event Day",
    ],
  },
  {
    layoutid: "011",
    name: "Violet Blossom",
    category: "Wedding",
    originalPrice: "RM60.00",
    discountedPrice: "RM50.00",
    images: [
      "/media/cardSelection/card-11/main.png",
      "/media/cardSelection/card-11/2-image.png",
    ],
    description:
      "Designed during Spring season. Violet Blossom is potraiting how one of the meaning og beauty that can be significant to flowers blooming. With purple as its main theme color, surely this will suits your big day!",
    demo: "/layout11-example",
    features: [
      "RSVP + Admin Dashboard incl.",
      "Wishes",
      "Google Map Location / Waze Location",
      "Choose any song from Youtube",
      "Link to Whatsapp & Phone Call",
      "Add Photo section (Upon request)",
      "Live support during Event Day",
    ],
  },
  {
    layoutid: "012",
    name: "Green Leaf",
    category: "Wedding",
    originalPrice: "RM60.00",
    discountedPrice: "RM50.00",
    images: [
      "/media/cardSelection/card-12/main.png",
      "/media/cardSelection/card-12/2-image.png",
    ],
    description:
      "Inspired by the beauty of nature, Green leaf is a symbol for green theme colors that potrays nature mixed with art",
    demo: "/layout12-example",
    features: [
      "RSVP + Admin Dashboard incl.",
      "Wishes",
      "Google Map Location / Waze Location",
      "Choose any song from Youtube",
      "Link to Whatsapp & Phone Call",
      "Add Photo section (Upon request)",
      "Live support during Event Day",
    ],
  },
];
