import { FontFamilyConfig } from "@/pages/e-invite/edit/[eInviteId]";

export interface AssetLayoutProps {
  fontFamily?: FontFamilyConfig;
  textFontFamily?: FontFamilyConfig;
  bgColor?: string;
  headerImage?: string;
  bodyImage?: string;
  widgetBgColor?: string;
  widgetColor?: string;
  widgetWsCta?: string;
  widgetMapCta?: string;
  title1?: string;
  title1Color?: string;
  title1Size?: string;
  title1Pos?: string;
  title1Shadow?: string;
  title2?: string;
  title2Color?: string;
  title2Size?: string;
  title2Pos?: string;
  title2Shadow?: string;
  description1?: string;
  description1Color?: string;
  description1Size?: string;
  description1Pos?: string;
  description1TopSpacing?: string;
  description1BotSpacing?: string;
  description2?: string;
  description2Color?: string;
  description2Size?: string;
  description2Pos?: string;
  description2TopSpacing?: string;
  description2BotSpacing?: string;
  description3?: string;
  description3Color?: string;
  description3Size?: string;
  description3Pos?: string;
  description3TopSpacing?: string;
  description3BotSpacing?: string;
  description4?: string;
  description4Color?: string;
  description4Size?: string;
  description4Pos?: string;
  description4TopSpacing?: string;
  description4BotSpacing?: string;
}
